# Azure OpenAI O1 Configuration
AZURE_OPENAI_O1_API_KEY = "${AZURE_OPENAI_O1_API_KEY}"
AZURE_OPENAI_O1_ENDPOINT = "${AZURE_OPENAI_O1_ENDPOINT}"
AZURE_OPENAI_O1_DEPLOYMENT = "${AZURE_OPENAI_O1_DEPLOYMENT}"

# Azure OpenAI O1 Mini Configuration
AZURE_OPENAI_O1_MINI_API_KEY = "${AZURE_OPENAI_O1_MINI_API_KEY}"
AZURE_OPENAI_O1_MINI_ENDPOINT = "${AZURE_OPENAI_O1_MINI_ENDPOINT}"
AZURE_OPENAI_O1_MINI_DEPLOYMENT = "${AZURE_OPENAI_O1_MINI_DEPLOYMENT}"

# API Version
AZURE_OPENAI_API_VERSION = "2024-02-15" 