# Azure OpenAI O1 Configuration
AZURE_OPENAI_O1_ENDPOINT = "https://ai-synthiq2181159623886.openai.azure.com/openai/deployments/o1/chat/completions?api-version=2024-12-01-preview"
AZURE_OPENAI_O1_API_KEY = "e2d5cea61f4f415fa311b53560caef60"
AZURE_OPENAI_O1_DEPLOYMENT = "o1"

# Azure OpenAI O1 Mini Configuration
AZURE_OPENAI_O1_MINI_ENDPOINT = "https://ai-synthiqnew691201261834.openai.azure.com/openai/deployments/o1-mini/chat/completions?api-version=2024-08-01-preview"
AZURE_OPENAI_O1_MINI_API_KEY = "4db1fdde020e4547a3f47e837df430db"
AZURE_OPENAI_O1_MINI_DEPLOYMENT = "o1-mini"

# API Version
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"

# Perplexity API
PERPLEXITY_API_KEY = "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" 